title: norns community
description: a script index for the monome norns sound computer
baseurl: /norns-community
url: https://vaporwavemall.com
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
include: ['_pages']
