title: norns community
description: a script index for the monome norns sound computer
baseurl: /
url: https://norns.community
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
include: ['_pages']
